This notebook is for exploring the Week 1 collected data.

In [102]:
#Import some relevant packages
import csv
import requests

#For working with SQL in Python
from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists, create_database
import psycopg2

#For generally exploring things within Python
import pandas as pd
import matplotlib as mpl
import numpy as np

In [2]:
hot_this_week = pd.read_csv('lots_of_reviews_006.csv', index_col=0)

In [3]:
hot_this_week = pd.read_csv('lots_of_reviews_003.csv')
hot_this_week.head()

,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,evalDate,image,logistics,skuInfo,thumbnail
0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",NaN,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,31 Aug 2018,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...,China Post Registered Air Mail,Color:khaki and yellow Size:56to60cm,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...
1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,28 Aug 2018,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...,ePacket,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...
2,32243608596,False,US,100,NaN,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,10 Sep 2018,NaN,ePacket,Color:black and khaki Size:56to60cm,NaN
3,32243608596,False,US,100,NaN,NaN,NaN,1616342783,R****r S.,10 Sep 2018,NaN,AliExpress Standard Shipping,Color:black and khaki Size:56to60cm,NaN
4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,18 Aug 2018,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...,AliExpress Standard Shipping,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...

In [4]:
new_header = hot_this_week.columns.values
print(new_header)

['product_id' 'anonymous' 'buyerCountry' 'buyerEval' 'buyerFeedback'
 'buyerGender' 'buyerHeadPortrait' 'buyerId' 'buyerName' 'evalDate'
 'image' 'logistics' 'skuInfo' 'thumbnail']

In [9]:
df_bad_header = pd.read_csv('lots_of_reviews_005.csv')
df_bad_header.head()

,32317979982,False,US,100,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,Unnamed: 5,Unnamed: 6,1611199947,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg_220x220.jpg
0,32317979982,False,US,100,"Очень красивый, яркий купальник на девочку 9-1...",NaN,NaN,1.738247e+09,Y****a S.,10 Jun 2018,NaN,China Post Registered Air Mail,Color:A Size:12,NaN
1,32317979982,False,US,80,quality is very good but size is very Small. I...,NaN,NaN,9.192527e+08,A**a T.,19 May 2018,NaN,China Post Registered Air Mail,Color:A Size:8,NaN
2,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:B Size:8,NaN
3,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.387970e+08,A***a M.,07 Jul 2018,NaN,ePacket,Color:A Size:8,NaN
4,32317979982,False,US,100,NaN,NaN,NaN,1.662058e+08,S******u M.,22 May 2018,NaN,ePacket,Color:B Size:12,NaN

In [11]:
bad_headers=df_bad_header.columns.values

In [14]:
header_dict = dict(zip(bad_headers,new_header))

In [15]:
df_bad_header.rename(columns = header_dict)

,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,evalDate,image,logistics,skuInfo,thumbnail
0,32317979982,False,US,100,"Очень красивый, яркий купальник на девочку 9-1...",NaN,NaN,1.738247e+09,Y****a S.,10 Jun 2018,NaN,China Post Registered Air Mail,Color:A Size:12,NaN
1,32317979982,False,US,80,quality is very good but size is very Small. I...,NaN,NaN,9.192527e+08,A**a T.,19 May 2018,NaN,China Post Registered Air Mail,Color:A Size:8,NaN
2,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:B Size:8,NaN
3,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.387970e+08,A***a M.,07 Jul 2018,NaN,ePacket,Color:A Size:8,NaN
4,32317979982,False,US,100,NaN,NaN,NaN,1.662058e+08,S******u M.,22 May 2018,NaN,ePacket,Color:B Size:12,NaN
5,32317979982,False,US,100,NaN,NaN,NaN,8.807269e+08,C*****a W.,31 Mar 2018,NaN,AliExpress Standard Shipping,Color:A Size:8,NaN
6,32317979982,True,US,80,NaN,NaN,NaN,NaN,AliExpress Shopper,23 May 2018,NaN,AliExpress Standard Shipping,Color:A Size:12,NaN
7,32317979982,True,US,100,NaN,NaN,NaN,NaN,AliExpress Shopper,03 Aug 2018,NaN,China Post Registered Air Mail,Color:B Size:12,NaN
8,32317979982,True,US,80,image et produit correspondent,NaN,NaN,NaN,AliExpress Shopper,30 Apr 2018,NaN,AliExpress Standard Shipping,Color:A Size:8,NaN
9,32317979982,False,US,80,NaN,NaN,NaN,1.726295e+09,V***a B.,16 Apr 2018,NaN,China Post Registered Air Mail,Color:A Size:10,NaN
10,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:A Size:8,NaN
11,32317979982,False,US,100,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,NaN,NaN,1.611200e+09,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43J...,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43J...
12,32317979982,False,US,100,"Очень красивый, яркий купальник на девочку 9-1...",NaN,NaN,1.738247e+09,Y****a S.,10 Jun 2018,NaN,China Post Registered Air Mail,Color:A Size:12,NaN
13,32317979982,False,US,80,quality is very good but size is very Small. I...,NaN,NaN,9.192527e+08,A**a T.,19 May 2018,NaN,China Post Registered Air Mail,Color:A Size:8,NaN
14,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:B Size:8,NaN
15,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.387970e+08,A***a M.,07 Jul 2018,NaN,ePacket,Color:A Size:8,NaN
16,32317979982,False,US,100,NaN,NaN,NaN,1.662058e+08,S******u M.,22 May 2018,NaN,ePacket,Color:B Size:12,NaN
17,32317979982,False,US,100,NaN,NaN,NaN,8.807269e+08,C*****a W.,31 Mar 2018,NaN,AliExpress Standard Shipping,Color:A Size:8,NaN
18,32317979982,True,US,80,NaN,NaN,NaN,NaN,AliExpress Shopper,23 May 2018,NaN,AliExpress Standard Shipping,Color:A Size:12,NaN
19,32317979982,True,US,100,NaN,NaN,NaN,NaN,AliExpress Shopper,03 Aug 2018,NaN,China Post Registered Air Mail,Color:B Size:12,NaN
20,32317979982,True,US,80,image et produit correspondent,NaN,NaN,NaN,AliExpress Shopper,30 Apr 2018,NaN,AliExpress Standard Shipping,Color:A Size:8,NaN
21,32317979982,False,US,80,NaN,NaN,NaN,1.726295e+09,V***a B.,16 Apr 2018,NaN,China Post Registered Air Mail,Color:A Size:10,NaN
22,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:A Size:8,NaN
23,32317979982,False,US,100,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,NaN,NaN,1.611200e+09,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43J...,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43J...
24,32317979982,False,US,100,"Очень красивый, яркий купальник на девочку 9-1...",NaN,NaN,1.738247e+09,Y****a S.,10 Jun 2018,NaN,China Post Registered Air Mail,Color:A Size:12,NaN
25,32317979982,False,US,80,quality is very good but size is very Small. I...,NaN,NaN,9.192527e+08,A**a T.,19 May 2018,NaN,China Post Registered Air Mail,Color:A Size:8,NaN
26,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.254183e+08,M*****a S.,29 May 2018,NaN,ePacket,Color:B Size:8,NaN
27,32317979982,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,7.387970e+08,A***a M.,07 Jul 2018,NaN,ePacket,Color:A Size:8,NaN
28,32317979982,False,US,100,NaN,NaN,NaN,1.662058e+08,S******u M.,22 May 2018,NaN,ePacket,Color:B Size:12,NaN
29,32317979982,False,US,100,NaN,NaN,NaN,8.807269e+08,C*****a W.,31 Mar 2018,NaN,AliExpress Standard Shipping,Color:A Size:8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2117,32261078955,False,US,100,NaN,NaN,NaN,9.112784e+08,E***a K.,03 Sep 2018,NaN,Cainiao Super Economy,Color:Dark Brown,NaN
2118,2027803414,False,US,100,NaN,NaN,NaN,7.630024e+08,B*****a L.,20 Jun 2018,NaN,China Post Ordinary Small Packet Plus,Color:A Material:For iphone 7Plus,NaN
2119,2027803414,True,US,100,NaN,NaN,NaN,NaN,AliExpress Shopper,15 Jul 2018,NaN,China Post Ordinary Small Packet Plus,Color:A Material:For J5 2017 EU,NaN
2120,2027803414,False,US,100,NaN,NaN,NaN,1.680869e+09,B******n K.,10 May 2018,NaN,China Post Ordinary Small Packet Plus,Color:B Material:For J3 And J3 2016,NaN
2121,2027803414,False,US,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,1.660714e+09,L***e G.,17 Apr 2018,NaN,China Post Ordinary Small Packet Plus,Color:E Material:For Samsung S8 Plus,NaN
2122,2027803414,True,US,80,NaN,NaN,NaN,NaN,AliExpress Shopper,16 Apr 2018,NaN,China Post Ordinary Small Packet Plus,Color:C Material:For J5 2016 J510,NaN
2123,2027803414,False,US,80,NaN,NaN,NaN,1.760134e+09,T****a H.,01 May 2018,NaN,China Post Ordinary Small Packet Plus,Color:C Material:For A3 2017 A320,NaN
2124,2027803414,False,RU,100,NaN,F,https://gw.alicdn.com/tps/TB1zA01LXXXXXc0XFXXX...,1.616220e+09,M*****2 N.,29 Jul 2018,NaN,AliExpress Saver Shipping,Color:A Material:For J7 2016 J710,NaN
2125,32235517648,False,US,100,пришло до кемерово быстро по качеству всё гуд,NaN,NaN,8.833521e+08,K********n T.,18 Apr 2018,NaN,Russian Air,Color:60pcs green,NaN
2126,32235517648,False,US,100,NaN,NaN,NaN,1.611392e+09,I**r Z.,03 Jul 2018,NaN,Russian Air,Color:60pcs black,NaN
2127,32235517648,False,US,100,NaN,NaN,NaN,8.902373e+08,P**l A.,30 Jul 2018,NaN,ePacket,Color:100pcs black,NaN
2128,32235517648,True,US,100,NaN,NaN,NaN,NaN,AliExpress Shopper,26 Mar 2018,NaN,Russian Air,Color:100pcs colorized,NaN
2129,1659437086,False,US,100,Produto muito bom.Atendeu as minhas expectativ...,NaN,https://ae01.alicdn.com/kf/UTB8VpOBl8ahduJk43J...,8.007315e+08,P***o S.,30 Jun 2018,https://ae01.alicdn.com/kf/UTB8m7PjAWrFXKJk43O...,ePacket,Color:Hooded Green Size:L,https://ae01.alicdn.com/kf/UTB8m7PjAWrFXKJk43O...
2130,1659437086,True,US,80,NaN,NaN,NaN,NaN,AliExpress Shopper,12 Sep 2018,NaN,AliExpress Standard Shipping,Color:Black Size:XXL,NaN
2131,1659437086,True,US,100,rápido envío y muy bien empacado. probaré el p...,NaN,NaN,NaN,AliExpress Shopper,15 Aug 2018,NaN,AliExpress Standard Shipping,Color:Hooded Green Size:L,NaN
2132,1659437086,False,US,100,"PRODUTO MUITO BOM, E A SEGUNDA COMPRA QUE FAÇO...",NaN,NaN,1.684040e+08,A**x S.,07 May 2018,NaN,HongKong Post Air Mail,Color:Hooded Green Size:L,NaN
2133,1659437086,False,US,100,Очень долгая доставка. В остальном все хорошо.,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,1.443129e+08,F***d F.,14 Jun 2018,NaN,China Post Registered Air Mail,Color:Hooded Green Size:XL,NaN
2134,1659437086,False,US,100,I am satisfied. it was all right,NaN,NaN,9.168483e+08,M****l M.,06 Apr 2018,NaN,AliExpress Standard Shipping,Color:Hooded Green Size:M,NaN
2135,1659437086,False,US,40,"Boa tarde, o zíper não funciona como deveria, ...",NaN,NaN,1.690581e+09,M***a I.,27 Mar 2018,NaN,ePacket,Color:Orange Size:4XL,NaN
2136,1659437086,False,US,100,NaN,NaN,NaN,8.766697e+08,M*****a S.,03 Sep 2018,NaN,AliExpress Standard Shipping,Color:Hooded Green Size:M,NaN
2137,1659437086,False,US,100,NaN,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,9.002542e+08,J*s V.,03 Jul 2018,NaN,China Post Registered Air Mail,Color:Hooded Green Size:XXL,NaN
2138,1659437086,False,US,100,NaN,NaN,https://ae01.alicdn.com/kf/UT8XYGkXKlXXXagOFbX...,1.382712e+08,I**r M.,04 May 2018,NaN,AliExpress Standard Shipping,Color:Hooded Green Size:4XL,NaN
2139,1659437086,False,US,100,NaN,NaN,https://ae01.alicdn.com/kf/UTB8ZNJBANHEXKJk43J...,1.611517e+09,A****y G.,04 May 2018,NaN,China Post Registered Air Mail,Color:Black Size:XL,NaN
2140,1659437086,False,US,100,NaN,NaN,NaN,1.615314e+09,L*************n N.,31 Aug 2018,NaN,AliExpress Standard Shipping,Color:Hooded Green Size:XL,NaN
2141,1659437086,False,US,80,NaN,NaN,NaN,8.712516e+08,M***n S.,06 Apr 2018,NaN,AliExpress Standard Shipping,Color:Green Black Size:L,NaN
2142,1659437086,True,US,80,NaN,NaN,NaN,NaN,AliExpress Shopper,21 Apr 2018,NaN,AliExpress Standard Shipping,Color:Green Size:4XL,NaN
2143,1659437086,False,US,100,NaN,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,1.784086e+09,A*****j C.,15 Jul 2018,NaN,China Post Registered Air Mail,Color:Green Black Size:4XL,NaN
2144,1659437086,False,US,40,The size is so different,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,8.922826e+08,A***e V.,30 Apr 2018,NaN,ePacket,Color:Hooded Green Size:L,NaN
2145,1659437086,False,US,100,NaN,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,8.922826e+08,A***e V.,19 May 2018,NaN,ePacket,Color:Hooded Green Size:XXL,NaN
2146,1659437086,False,US,100,"Produto muito bom, vale muito apena. Sempre co...",NaN,NaN,1.684040e+08,A**x S.,16 Apr 2018,NaN,China Post Registered Air Mail,Color:Hooded Green Size:L,NaN

In [10]:
big_df = pd.read_csv('all_reviews_17_09_18.csv', index_col=0, low_memory=False)

In [11]:
big_df.shape

(125384, 28)

In [5]:
def load_df_replace_header(filename):
    df = pd.read_csv(filename)
    bad_headers = df.columns.values
    header_dict = dict(zip(bad_headers,new_header))
    df_new_heads = df.rename(columns=header_dict)
    return df_new_heads

In [21]:
df_current = load_df_replace_header('garden_reviews_001.csv')

In [22]:
df_current.head()

,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,evalDate,image,logistics,skuInfo,thumbnail
0,32470856363,True,US,100,Excelent condition and fast delivery. I will b...,M,NaN,NaN,AliExpress Shopper,13 Aug 2018,NaN,Seller's Shipping Method,NaN,NaN
1,32470856363,False,US,100,Arrived quickly and in great shape. Thank you.,M,https://ae01.alicdn.com/kf/UT8NVTIXWhaXXagOFbX...,8.713801e+08,R*****n J.,30 Mar 2018,NaN,Seller's Shipping Method,NaN,NaN
2,32470856363,False,US,100,NaN,M,https://gw.alicdn.com/tps/TB1CjX4LXXXXXbSXFXXX...,9.215386e+08,J***o V.,12 Sep 2018,NaN,Seller's Shipping Method,NaN,NaN
3,32470856363,False,US,100,NaN,M,https://ae01.alicdn.com/kf/UTB8XGw9XKvJXKJkSaj...,1.422593e+08,F***k B.,22 Aug 2018,NaN,Seller's Shipping Method,NaN,NaN
4,32470856363,False,US,80,NaN,NaN,NaN,1.661878e+09,H*****a H.,24 Aug 2018,NaN,Yanwen Economic Air Mail,NaN,NaN

In [23]:
big_df_5 = pd.concat([big_df_4,df_current], ignore_index = True, sort=False)

In [24]:
big_df_now = big_df_5
big_df_now.shape

(136308, 28)

In [25]:
big_df_now.to_csv('all_reviews_18_09_18.csv')

In [26]:
big_df_now['buyerFeedback']

0         Great fabric and quality, fast delivery and co...
1         Me gusto mucho igual que la presentación, nada...
2                                                       NaN
3                                                       NaN
4                                                   thanks!
5                                    not bad for such price
6                                                       NaN
7         nice cap, my boyfriend is very happy with it. ...
8                                   Good just little stain
9                                                       NaN
10                                 perfect, adjustable size
11                              All stained. Terrible goods
12                                                      NaN
13        Well made. Seems to be a one size fits all of ...
14                                                      NaN
15        Nice cap in good quality. Oryginally was too b...
16        love the hat, nice design, affordable price, g...
17        кепка хорошая. качество норм. нитки не торчат....
18        They sent me the wrong hat. I want to get the ...
19                Качество хорошее, кепка удобная. Спасибо.
20        Пришла за месяц до Калининграда. Качество норм...
21        A little lighter in colour compared to photos ...
22        no es en color que pedì .... quérir el color r...
23        pretty fast shipment,one week to Japan!\ngood ...
24        Цвет не совсем как на самом деле. Качество сре...
25        кепочка классная! заказала для мужа, но думаю ...
26        encaja perfectamente con la descripción, muy c...
27        Выглядит замечательно. Полностью соответствует...
28        Хорошая кепка. приятная на ощупь. немного туск...
29        amazing product, perfect fit. fast shipping. w...
                                ...
136278    20 days the transport,in good safe packaging,c...
136279    Одна пришла хорошая другая раздавленная очень ...
136280    Я очень рада,что на ютубе увидела это растение...
136281    товар соответствует описанию.  но есть один ми...
136282    Доставка до Москвы около месяца, трек не отсле...
136283                                                  NaN
136284    заказ был сделан 20.07 и пришёл 29.08, упакова...
136285    La Rosa è arrivata abbastanza velocemente ma n...
136286           Прислали такую шнягу, подождём, посмотрим.
136287    Товар получила. Упаковка ужасное. Шёл долго. П...
136288    доставка больше месяца,  товар соответствует о...
136289    заказ пришёл после срока.посмотрим что из этог...
136290    все\n отлично. соответствует описанию. на фото...
136291    Растения мертвые. Корней не образуют. Фото чер...
136292    Соответствует описанию. после погружения в вод...
136293    Очень классное растение! Роза Иерихона. Цена к...
136294    товар получил, заказал две розы, продавец отпр...
136295    Доставка 1,5 месяца в Нижний Новгород. Упакова...
136296    Even when it is bloom after watering, the leav...
136297    Очень крутая штука.пришла полностью сухая чере...
136298    These are really cool put in water and they gr...
136299    Цветок пришёл, немного с задержкой. Спасибо бо...
136300    Супер! первое фото через час после распаковки,...
136301    Заказ шёл очень долго. Почти два месяца. Цвето...
136302    Доставка быстрая- меньше месяца до Волгограда....
136303                                                  NaN
136304                                                  NaN
136305                                                  NaN
136306                                                  NaN
136307                                                  NaN
Name: buyerFeedback, Length: 136308, dtype: object

In [3]:
import matplotlib.pyplot as plt

In [27]:
big_df = pd.read_csv('all_reviews_18_09_18.csv', index_col=0, low_memory=False)
big_df.head()

,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,evalDate,...,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,Unnamed: 5,Unnamed: 6,1611199947,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg_220x220.jpg
0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",NaN,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,31 Aug 2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,28 Aug 2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,32243608596,False,US,100,NaN,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,10 Sep 2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,32243608596,False,US,100,NaN,NaN,NaN,1616342783,R****r S.,10 Sep 2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,18 Aug 2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
common_reviewers = big_df['buyerId'].value_counts()

In [29]:
common_reviewers

104950247.0     275
1679959340.0    144
buyerId          56
188642918.0      55
120095941.0      23
729546716.0      17
753376930.0      16
230978574.0      15
728817668.0      15
729520432.0      13
924723896.0      11
1651236413.0     11
904767815.0      10
890507421.0      10
195417695.0      10
927315042.0      10
1612767300.0      9
703013617.0       9
138744143.0       9
1795716940.0      9
136764225.0       8
916342631.0       8
138655426.0       8
910381248.0       8
786456751.0       8
728763918.0       8
793853785.0       8
186883328.0       8
732322611.0       8
1787142919.0      7
               ...
761554695.0       1
911142376.0       1
185623349.0       1
875682314.0       1
179653678.0       1
776297971.0       1
840353699.0       1
188332002.0       1
713860046.0       1
776243700.0       1
141764987.0       1
783027896.0       1
143318165.0       1
713857696.0       1
170808340.0       1
706057902.0       1
1647142336.0      1
183360258.0       1
746966272.0       1
781085474.0       1
855745448.0       1
141022634.0       1
1649268060.0      1
1659961211.0      1
179322598.0       1
135751197.0       1
176637713.0       1
764334950.0       1
752555077.0       1
865323386.0       1
Name: buyerId, Length: 104632, dtype: int64

In [14]:
%matplotlib inline
plt.pie(common_reviewers)

NameError: name 'plt' is not defined

In [16]:
reviewer_profile = big_df.loc[big_df['buyerId']>188642917]
reviewer_profile.head()

TypeError: '>' not supported between instances of 'str' and 'int'

# Put reviews in a SQL database

In [30]:
#Make a Database
# Define a database name (we're using a dataset on reviews, so we'll call it reviews_db)
# Set your postgres username
dbname = 'reviews_db'
username = 'rebeccareitz' # change this to your username

## 'engine' is a connection to a database
## Here, we're using postgres, but sqlalchemy can connect to other things too.
engine = create_engine('postgres://%s@localhost/%s'%(username,dbname))
print(engine.url)

## create a database (if it doesn't exist)
if not database_exists(engine.url):
    create_database(engine.url)
print(database_exists(engine.url))

postgres://rebeccareitz@localhost/reviews_db
True

In [31]:
## insert data into database from Python (proof of concept - this won't be useful for big data, of course)
big_df.to_sql('review_table', engine, if_exists='replace')

In [49]:
#Connect and query

# Connect to make queries using psycopg2
con = None
con = psycopg2.connect(database = dbname, user = username)

# query:
sql_query = """
SELECT * FROM review_table;
"""
review_data_from_sql = pd.read_sql_query(sql_query,con)
review_data_from_sql.head()

,index,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,...,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,Unnamed: 5,Unnamed: 6,1611199947,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg_22
0,0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",None,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,...,None,None,None,NaN,None,None,None,None,None,None
1,1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,...,None,None,None,NaN,None,None,None,None,None,None
2,2,32243608596,False,US,100,None,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,...,None,None,None,NaN,None,None,None,None,None,None
3,3,32243608596,False,US,100,None,None,None,1616342783,R****r S.,...,None,None,None,NaN,None,None,None,None,None,None
4,4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,...,None,None,None,NaN,None,None,None,None,None,None

In [45]:
# new query:
sql_query = """
SELECT * FROM review_table
WHERE anonymous = 'False';
"""
review_data_from_sql = pd.read_sql_query(sql_query,con)
review_data_from_sql.head()

,index,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,...,ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.,Unnamed: 5,Unnamed: 6,1611199947,M****a C.,12 Jul 2018,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg,ePacket,Color:A Size:10,https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg_22
0,0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",None,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,...,None,None,None,None,None,None,None,None,None,None
1,1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,...,None,None,None,None,None,None,None,None,None,None
2,2,32243608596,False,US,100,None,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,...,None,None,None,None,None,None,None,None,None,None
3,3,32243608596,False,US,100,None,None,None,1616342783,R****r S.,...,None,None,None,None,None,None,None,None,None,None
4,4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,...,None,None,None,None,None,None,None,None,None,None

In [50]:
# actually relevent query:
sql_query = """
SELECT * FROM review_table
WHERE buyerId = '104950247';
"""
review_data_from_sql = pd.read_sql_query(sql_query,con)
review_data_from_sql.head()

DatabaseError: Execution failed on sql '
SELECT * FROM review_table
WHERE buyerId = '104950247';
': column "buyerid" does not exist
LINE 3: WHERE buyerId = '104950247';
              ^
HINT:  Perhaps you meant to reference the column "review_table.buyerId".

In [53]:
review_data_from_sql.buyerId.dtype

dtype('O')

In [54]:
review_data_from_sql['buyerId'].astype(str)

0            230419691
1           1678569385
2            127741530
3           1616342783
4            890393619
5           1693179945
6            134061513
7           1673192723
8           1663867706
9            919433626
10           877031618
11           725446934
12          1633590934
13          1697140394
14           901073898
15           873791448
16           870521201
17          1612350942
18          1620213964
19           196999326
20                None
21           753293540
22           197641598
23           876629396
24           714878106
25           161195996
26           141857290
27           169087188
28          1828596620
29           184234590
              ...
136278     170237945.0
136279     756416539.0
136280     832497086.0
136281     862967191.0
136282    1715047284.0
136283            None
136284     731869075.0
136285     817305291.0
136286     767255962.0
136287    1771972982.0
136288     185024259.0
136289            None
136290     745940826.0
136291     831050217.0
136292     118568883.0
136293            None
136294     823009414.0
136295     736225456.0
136296     700675021.0
136297     190619206.0
136298     902948642.0
136299     841684060.0
136300     192149404.0
136301    1733574336.0
136302     835411901.0
136303     846606188.0
136304    1693002143.0
136305     188676976.0
136306            None
136307     748316670.0
Name: buyerId, Length: 136308, dtype: object

In [56]:
big_df.isna().sum()

product_id                                                                    2147
anonymous                                                                     2147
buyerCountry                                                                  2156
buyerEval                                                                     2147
buyerFeedback                                                                32231
buyerGender                                                                  52530
buyerHeadPortrait                                                            46853
buyerId                                                                      18537
buyerName                                                                     2148
evalDate                                                                      2147
image                                                                        52727
logistics                                                                     2147
skuInfo                                                                      11705
thumbnail                                                                    52727
32317979982                                                                 134161
False                                                                       134161
US                                                                          134161
100                                                                         134161
ОТЛИЧНЫЙ КУПАЛЬНИК. ДЕВОЧКА 9 ЛЕТ.                                          134926
Unnamed: 5                                                                  135237
Unnamed: 6                                                                  135199
1611199947                                                                  134442
M****a C.                                                                   134161
12 Jul 2018                                                                 134161
https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg                135482
ePacket                                                                     134161
Color:A Size:10                                                             134595
https://ae01.alicdn.com/kf/UTB8eZ3GBhHEXKJk43Jeq6yeeXXaR.jpg_220x220.jpg    135482
dtype: int64

In [65]:
# actually relevent query:
sql_query = """
SELECT "product_id", "anonymous", "buyerCountry", "buyerEval", "buyerFeedback", "buyerGender", "buyerHeadPortrait",
"buyerId", "buyerName", "evalDate", "image", "logistics", "skuInfo", "thumbnail"
FROM review_table;
"""
review_data_from_sql = pd.read_sql_query(sql_query,con)
review_data_from_sql.head()

,product_id,anonymous,buyerCountry,buyerEval,buyerFeedback,buyerGender,buyerHeadPortrait,buyerId,buyerName,evalDate,image,logistics,skuInfo,thumbnail
0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",None,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,31 Aug 2018,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...,China Post Registered Air Mail,Color:khaki and yellow Size:56to60cm,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...
1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,28 Aug 2018,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...,ePacket,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...
2,32243608596,False,US,100,None,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,10 Sep 2018,None,ePacket,Color:black and khaki Size:56to60cm,None
3,32243608596,False,US,100,None,None,None,1616342783,R****r S.,10 Sep 2018,None,AliExpress Standard Shipping,Color:black and khaki Size:56to60cm,None
4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,18 Aug 2018,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...,AliExpress Standard Shipping,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...

In [66]:
review_data_from_sql.columns = map(str.lower, review_data_from_sql.columns)
review_data_from_sql.head()

,product_id,anonymous,buyercountry,buyereval,buyerfeedback,buyergender,buyerheadportrait,buyerid,buyername,evaldate,image,logistics,skuinfo,thumbnail
0,32243608596,False,US,100,"Great fabric and quality, fast delivery and co...",None,https://ae01.alicdn.com/kf/UTB8vTH0hFPJXKJkSah...,230419691,E***e L.,31 Aug 2018,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...,China Post Registered Air Mail,Color:khaki and yellow Size:56to60cm,https://ae01.alicdn.com/kf/UTB8gDRQB5aMiuJk43P...
1,32243608596,False,US,80,"Me gusto mucho igual que la presentación, nada...",F,https://ae01.alicdn.com/kf/UTB8lUMuipPJXKJkSah...,1678569385,M**a M.,28 Aug 2018,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...,ePacket,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8Ti3mBOaMiuJk43P...
2,32243608596,False,US,100,None,F,https://ae01.alicdn.com/kf/UTB8upYOXSbIXKJkSae...,127741530,V******a R.,10 Sep 2018,None,ePacket,Color:black and khaki Size:56to60cm,None
3,32243608596,False,US,100,None,None,None,1616342783,R****r S.,10 Sep 2018,None,AliExpress Standard Shipping,Color:black and khaki Size:56to60cm,None
4,32243608596,False,US,100,thanks!,F,https://ae01.alicdn.com/kf/UTB8eeCYxqrFXKJk43O...,890393619,E****************r N.,18 Aug 2018,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...,AliExpress Standard Shipping,Color:dark blue and red Size:56to60cm,https://ae01.alicdn.com/kf/UTB8A.mKiXfJXKJkSam...

In [67]:
review_data_from_sql.to_csv('all_reviews_18_09_18_clean.csv')

In [68]:
df = review_data_from_sql

In [73]:
df.buyerid.dtype

dtype('O')

In [72]:
df['buyerid']=df['buyerid'].astype(str)

In [74]:
df.to_sql('clean_review_table', engine, if_exists='replace')

In [78]:
# actually relevent query:
sql_query = """
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'clean_review_table';
"""
column_type = pd.read_sql_query(sql_query,con)
column_type

          column_name data_type
0               index    bigint
1          product_id      text
2           anonymous      text
3        buyercountry      text
4           buyereval      text
5       buyerfeedback      text
6         buyergender      text
7   buyerheadportrait      text
8             buyerid      text
9           buyername      text
10           evaldate      text
11              image      text
12          logistics      text
13            skuinfo      text
14          thumbnail      text

In [83]:
# actually relevent query:
sql_query = """
SELECT buyerid, buyerfeedback 
FROM clean_review_table
WHERE buyerid = '890393619';
"""
buyer_info = pd.read_sql_query(sql_query,con)
buyer_info

     buyerid buyerfeedback
0  890393619       thanks!

In [93]:
count_query = """
SELECT COUNT(buyerid), buyerid 
  FROM clean_review_table
  WHERE anonymous = 'False'
 GROUP BY buyerid
 ORDER BY COUNT(buyerid) DESC
"""
buyer_counts = pd.read_sql_query(count_query,con,coerce_float=True)
buyer_counts

        count       buyerid
0         275   104950247.0
1         144  1679959340.0
2         132          None
3          55   188642918.0
4          23   120095941.0
5          17   729546716.0
6          16   753376930.0
7          15   728817668.0
8          15   230978574.0
9          13   729520432.0
10         11   924723896.0
11         11  1651236413.0
12         10   904767815.0
13         10   927315042.0
14         10   195417695.0
15         10   890507421.0
16          9   703013617.0
17          9  1612767300.0
18          9  1795716940.0
19          9   138744143.0
20          8   138655426.0
21          8   186883328.0
22          8   136764225.0
23          8   786456751.0
24          8   916342631.0
25          8   732322611.0
26          8   910381248.0
27          8   793853785.0
28          8   728763918.0
29          7   808207764.0
...       ...           ...
104602      1   196222947.0
104603      1   196199279.0
104604      1   188590811.0
104605      1   188590999.0
104606      1   137141747.0
104607      1   196198648.0
104608      1   123899894.0
104609      1     196198179
104610      1   196221211.0
104611      1   196211551.0
104612      1   196201835.0
104613      1   196209788.0
104614      1   196216456.0
104615      1   132131426.0
104616      1   196216068.0
104617      1   196269995.0
104618      1   196244933.0
104619      1   196227745.0
104620      1   137148057.0
104621      1   132135981.0
104622      1   196228095.0
104623      1   161031655.0
104624      1   196242937.0
104625      1   196269925.0
104626      1   196256226.0
104627      1   196246862.0
104628      1   196253724.0
104629      1     196269090
104630      1   196267878.0
104631      1   196267879.0

[104632 rows x 2 columns]

In [96]:
sorted_buyers = pd.to_numeric(buyer_counts['buyerid'],errors='coerce')

In [101]:
#Make a good dataframe to work from
basic_query = """
SELECT *
  FROM clean_review_table
  WHERE anonymous = 'False'
"""
basic_df = pd.read_sql_query(count_query,con,coerce_float=True)
basic_df.head()

   count       buyerid
0    275   104950247.0
1    144  1679959340.0
2    132          None
3     55   188642918.0
4     23   120095941.0

In [98]:
# actually relevent query:
sql_query = """
SELECT buyerid, buyerfeedback 
FROM clean_review_table
WHERE buyerid = 1.049502e+08;
"""
buyer_info = pd.read_sql_query(sql_query,con)
buyer_info

DatabaseError: Execution failed on sql '
SELECT buyerid, buyerfeedback
FROM clean_review_table
WHERE buyerid = 1.049502e+08;
': operator does not exist: text = numeric
LINE 4: WHERE buyerid = 1.049502e+08;
                      ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.